use_frameworks!

platform :ios, '10.0'

target 'KJPlayer_Example' do
  pod 'KJPlayer', :path => '..'
  
  pod 'Then'
  pod 'SnapKit'
  pod 'FSPagerView'

  target 'KJPlayer_Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
